### ISSUE TITLE
Regarding timing options

### ISSUE THREAD

**Issue by felixbjorkeson** [b0nes164/GPUPrefixSums#14]
I have, on windows, used Nvidia Nsight Graphics to get detailed compute shader timings. Just build a Unity binary and launch it from Nsight. I assume a nvidia GPU is needed though.
![CaptureNsight](https://github.com/b0nes164/GPUPrefixSums/assets/66550440/968b823a-5170-4060-8d2f-be7f7383b4cd)

**Comment by b0nes164** [comment]
Hi @felixbjorkeson, thank you for your interest in this repo.

Unity does not expose GPU timestamps, which led to the indirect method of timing described in the readme. 

However the readme is outdated, and this issue has been remedied by the standalone D3D12 implementation. 

Furthermore collecting data based on single frame capture can be unreliable, and in general it is much more straightforward to use the timestamps exposed by the graphics API. 

I am closing this issue, but if you have any more questions, don't hesitate to ask.
