### ISSUE TITLE
Why Chained Scan with Decoupled Lookback isn't in main?

### ISSUE THREAD

**Issue by s1ddok** [b0nes164/GPUPrefixSums#4]
Hello! 

Thank you for this wonderful project and a great write-up, I've learned a lot!

I'm looking into porting the fastest algorithm from your repo into native HLSL/DirectX engine and I wonder why didn't you include Chained Scan with Decoupled Lookback as the main, fastest algo? is this due to this limitation:

> Currently the maximum aggregate sum supported in Chained Scan with Decoupled Lookback is 2^30.

? if so, do you think I should port this one, given that it suits my number of objects?

**Comment by b0nes164** [comment]
Hi @s1ddok, I apologize, Chained Scan with Decoupled Lookback is CD_Main_Vectorized. 

However, and partially in answer to your other issue, I'm pushing an update today that simplifies dispatchers, improves lookback phase code, improves the timing methodology and renames the files for clarity, so you should would wait for that before you port it over. For example, as you mentioned in your other issue, I moved initialization of `b_state` into `Init` kernel for clarity.

If you do get Chained Scan with Decoupled Lookback working in Metal, let me know, I would love to see it!

**Comment by b0nes164** [comment]
Alright, all the updates have been pushed to the main branch, let me know if you have any trouble with the implementation.

**Comment by s1ddok** [comment]
@b0nes164 wow thank you, I've already made some progress but will look into latest version now
